
void key_up();
void key_down();
void key_row_up();
void key_row_down();
void key_screan_up();
void key_screan_down();
void key_home();
void key_end();
void key_jump(int);
void key_jump_up(int);
void key_jump_down(int);
void key_rotate();
void key_rotate_document();
void key_quit();
void key_fullscreen();
void key_reload();
void key_this_page_has_number(int);
void key_set_columns(int);
void key_set_rows(int);
void click_distance(int first_x, int first_y, int second_x, int second_y);
void click_position(int x, int y);
void key_page_mode();
void key_zoom_mode();
